#!/usr/bin/env bash
function fhr () {
  find . -iname "*$**"
}
function rd() {
    rdesktop -g 1400x900 $*
}
function svndif() {
    svn diff  --diff-cmd colordiff $* | less;
}
function find_in() {
    find . -iname $1 | xargs grep $2 -sl
}
# bash
alias restart='sudo reboot'
alias shutdown='sudo halt'
alias apt-get='sudo apt-get'
alias root='sudo su -'
alias sp='source ~/.bash_profile'
alias nerd='vim +NERDTree'

# git
alias g="git"
alias gds='GIT_PAGER=cat git diff --stat'
alias grm="git status | grep deleted | awk '{print \$3}' | xargs git rm"
alias gs="git status -s"
alias gfa="git fetch --all"
alias gpl="git pull"
alias gap="git add -p"
alias gc="git commit"
alias gco="git checkout"

# ruby
alias b='bundle-hack'
alias bi='bundle-hack install'
alias be='bundle-exec-hack'
alias bl='bundle install --local'
alias guard='be guard'
alias r='rspec'
alias rff='r --fail-fast'
alias reado="\`~/bin/ssh-reagent\`"

alias enw='emacs -nw'
alias pg-start='pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start'
alias pg-stop='pg_ctl -D /usr/local/var/postgres stop -s -m fast'
alias v='vagrant'

alias untar='tar xvfz'
alias tfl='tail -Fn30 log/*.log'
alias c="clear"
alias retab="find . -iname '*.rb' | xargs sed -Ei '' 's/  /  /g'"
alias ey-meta='CLOUD_URL=https://cloud-meta.engineyard.com ey'
alias pt=papertrail
alias rff='r --fail-fast'
alias gmf='git merge --ff-only'
alias grep="grep --color"
alias egrep="egrep --color"
alias server='ssh eugene@server'
alias xbmc='ssh xbmc@192.168.1.4'
alias bridge="SSH_ORIGINAL_COMMAND='su - awsm' HADRIAN_AMAZON_ID='i-04f6cc7f' HADRIAN_FEATURES='base' ssh hadrian-meta"
alias buckman="SSH_ORIGINAL_COMMAND='su - deploy' HADRIAN_AMAZON_ID='i-c66b43ce' HADRIAN_FEATURES='base' ssh hadrian"
alias mission="SSH_ORIGINAL_COMMAND='su - deploy' HADRIAN_AMAZON_ID='i-fa99de93' HADRIAN_FEATURES='base' ssh hadrian"
alias temple="SSH_ORIGINAL_COMMAND='su - deploy' HADRIAN_AMAZON_ID='i-8dde41f6' HADRIAN_FEATURES='base' ssh hadrian"
alias smithy_staging="SSH_ORIGINAL_COMMAND='su - deploy' HADRIAN_AMAZON_ID='i-11ab2522' HADRIAN_FEATURES='base' ssh hadrian"
alias smithy_prod="SSH_ORIGINAL_COMMAND='su - deploy' HADRIAN_AMAZON_ID='i-913427e0' HADRIAN_FEATURES='base' ssh hadrian-meta"
alias digitalocean="ssh -p2200 eugene@107.170.158.208"
alias gitlab="ssh root@107.170.158.208"
