#!/usr/bin/env sh
## source cinderella bash completions
if [[ -d "$HOME/etc/bash_completion.d" ]] ; then
    source $HOME/etc/bash_completion.d/*.bash
fi

## Editor
if [[ -s $(which mvim) ]]; then
  export EDITOR=mvim
else
  export EDITOR=vim
fi

## PATH
PATH=$PATH:/usr/local/bin:/usr/local/git/bin/:/usr/local/sbin:/usr/local/Cellar/mysql55/5.5.30/bin/

## Set ls options per platform
if [[ $OSTYPE == 'linux-gnu' ]]; then
  alias ls='ls -p --color=auto'
elif [[ $OSTYPE == 'darwin10.0' ]]; then
  alias ls='ls -Gp'
fi

## Functions
function parse_git_dirty {
  [[ $(git status 2> /dev/null | tail -n1) != *"nothing to commit"* ]] && echo "*"
}
function parse_git_branch {
  git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e "s/* \(.*\)/[\1$(parse_git_dirty)]/"
}

## Prompt
if [[ -n "${SSH_CONNECTION+x}" ]]; then
  export PS1="\[\033[01;32m\]\u@\h\[\033[01;34m\] \H:\W \$(parse_git_branch)\$\[\033[00m\] "
else
  export PS1="\[\033[01;32m\]\u@\h\[\033[01;34m\] \W \$(parse_git_branch)\$\[\033[00m\] "
fi

if [ -n "$BASH_VERSION" ] || [ -n "$ZSH_VERSION" ]; then
  source /usr/local/share/chruby/chruby.sh
  source /usr/local/share/chruby/auto.sh
  chruby ruby-1.9
fi

RVM_PROMPT=$(which rvm-prompt 2>/dev/null);
CHRUBY=$(type -t chruby)

if [[ -s $RVM_PROMPT ]]; then
  export PS1="\$($RVM_PROMPT v g) $PS1"
elif [[ $CHRUBY == 'function' ]]; then
  CHRUBY_VERSION=$(chruby | awk '/\*/ {print $2}' | awk -F '-' '{print $2}')
  export PS1="$CHRUBY_VERSION $PS1"
fi

if [[ -s $(which keychain 2>/dev/null) ]]; then
  keychain ~/.ssh/id_rsa
fi

# homebrew git
PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH:/usr/local/bin"

#ls colors
export LS_COLORS="no=00:fi=00:di=01;34:ln=01;37:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:ex=01;35:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.gz=01;31:*.bz2=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.dmg=01;31:*.jpg=01;35:*.png=01;35:*.gif=01;35:*.bmp=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.png=01;35:*.mpg=01;35:*.avi=01;35:*.fli=01;35:*.gl=01;35:*.dl=01;35:*.pl=00;33:*.PL=00;33:*.pm=00;33:*.tt=00;33:*.yml=00;33:*.sql=00;33:*.html=00;33:*.css=00;33:*.js=00;33:*.rb=00;33:*.erb=00;33"
